---
all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_password: GetOff100
elasticsearch:
  hosts:
    el-instance:
      ansible_host: 172.22.75.34
kibana:
  hosts:
    ki-instance:
      ansible_host: 172.22.73.156
filebeat:
  hosts:
    fb-instance:
      ansible_host: 172.22.76.171