from centos
ENV TZ=Europe/moscow
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
RUN yum install -y epel-release
RUN yum install -y python3 openssh-server
RUN yum clean all
RUN systemctl start sshd

